
name: Documentation generation

on: push

jobs:
  generate_doc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: ls -la ..
      - name: Doxygen Action    
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: 'doc'
          doxyfile-path: 'api_doc/doxyfile' 
